### ISSUE TITLE
Create a github action that picks a message from a list predefined message and post it to our telegram channel

### ISSUE THREAD

**Issue by elhmn** [osscameroon/global-github-actions#3]
We have couple of message that needs to be published on a regular bases to our community, we need an action that will get messages from a list of predefined messages and publish them on a regular basis to telegram or twitter

**Comment by darixsamani** [comment]
how will the message list be stored?

**Comment by elhmn** [comment]
@darixsamani , unfortunately we already have someone working on it 👍

**Comment by elhmn** [comment]
This PR is solved by #25
