### ISSUE TITLE
fix: we don't want to post a quiz if poll's options are too long (>99 characters)

### ISSUE THREAD

**Issue by Sanix-Darker** [osscameroon/global-github-actions#55]
we don't want to post a quiz if poll's options are too long (>99 characters), as you can see on this github action : https://github.com/osscameroon/global-github-actions/runs/5206548120?check_suite_focus=true
![Screenshot from 2022-02-15 21-20-01](https://user-images.githubusercontent.com/22576758/154142946-761f60c0-c762-42e5-ba70-80bbc5176aad.png)
wha i suggest is to be sure that options are good before trying to send the first message, what do you think @pythonbrad

**Comment by pythonbrad** [comment]
>99 characters is for each quiz ?

**Comment by pythonbrad** [comment]
yes, then if one option exceed 99 character, the quiz will be skipped?

**Comment by pythonbrad** [comment]
A new quiz will be submit instead.

What do you think about create a function like propose_quiz who will be called in the main instead ?
```sh
main(){
    # until the quiz is proposed correctly
    while [ ! propose_quiz ]; do
        propose_quiz
    done
}
```
