### ISSUE TITLE
fix: Problem to escape quote

### ISSUE THREAD

**Issue by pythonbrad** [osscameroon/global-github-actions#58]
The bot don't escape well the quiz who contains quotes.
Eg: (How do you write "Hello World" in PHP) becomes (How do you write)

![a](https://user-images.githubusercontent.com/45305909/154665006-57c86c1e-acb7-44f0-9d24-fe0388b3a80d.png)

**Comment by pythonbrad** [comment]
The quiz message was not escaped. I propose this pull request #59

**Comment by Sanix-Darker** [comment]
Thanks for this contribution @pythonbrad !
