### ISSUE TITLE
PR Notification failed due to long description

### ISSUE THREAD

**Issue by FanJups** [osscameroon/global-github-actions#77]
https://github.com/osscameroon/js-generator/runs/6240271916?check_suite_focus=true

**Comment by pythonbrad** [comment]
@FanJups, is this issue still available?

**Comment by FanJups** [comment]
I think it's solved already @pythonbrad

**Comment by pythonbrad** [comment]
> I think it's solved already

Cool,then I suppose the issue can be close.
