### ISSUE TITLE
test: add a notifier for the broken links present in the websites.

### ISSUE THREAD

**Issue by pythonbrad** [osscameroon/global-github-actions#97]
## Introduction
The [broken_link_checker](https://github.com/osscameroon/broken_link_checker) of osscameroon is actually able to track all the broken link in a website.

## Problem
While the checking of osscameroon.com and blog.osscameroon.com, some broken links have been tracked. But, how to inform the osscameroon community to fix this problem?

## Solution
A github action can be create to alert the community, when a broken link is detected.

## Preview
![a](https://user-images.githubusercontent.com/45305909/192014707-d3189bf8-dd22-41f9-b17b-e6483e7ac587.png)

**Comment by Sanix-Darker** [comment]
Amazing work there !!!
Well done !
